### ISSUE TITLE
Unattended upgrades not working

### ISSUE THREAD

**Issue by LukeShortCloud** [jurassicplayer/decky-autoflatpaks#13]
Versions used:

- SteamOS 3.4.8
    - Later on, I updated to SteamOS 3.4.11. Same results.
- AutoFlatpaks 1.6.5

With a fresh install of AutoFlatpaks, I enabled unattended upgrades and set the interval to 1 hour for testing.

**Problem 1 = Flatpaks are never upgraded.** I first tried to turn my Steam Deck off for 2 hours and then turned it on. I then tried leaving it on for 2 hours straight. It never updated the Flatpaks either way. Watching the running processes, all I ever noticed was a check for possible updates when I first turn on my Steam Deck.

```
(deck@steamdeck ~)$ ps faux | grep -i flatpak
deck        2597  0.0  0.0   6564  2308 pts/0    S+   13:05   0:00              \_ grep --color=auto -i flatpak
root        2477 97.5  1.4 522852 176664 ?       Rl   13:05   0:01          \_ flatpak remote-ls --columns=name:f,installed-size:f,description:f,download-size:f,version:f,commit:f,branch:f,ref:f,origin:f,application:f,runtime:f,arch:f,options:f
```

**Problem 2 = Notifications do not match what the plugin menu says.** For example, when I turn on my Steam Deck, it always says `Updating 43 packages...`. But when I look at the Decky Loader plugin menu for AutoFlatpaks, it always says `36 updates available`. Also, the wording of "Updating X packages" makes it sound like it should be upgrading Flatpaks but that never happens.

**Comment by jurassicplayer** [comment]
Do you happen to have flatpaks that are installed as user or in a separate installation location (`/etc/flatpak/installations.d/...`)? At the moment, AutoFlatpaks can only handle the stock vanilla setup, which is having all flatpaks installed to system and no extra installation locations.

For the notifications, when AutoFlatpaks has that notification, it actually is attempting to upgrade them (just nothing to verify whether it failed or not), but in the case of having user/separate install locations, the flatpak cli usually prompts the user for input which AutoFlatpak just fails on atm.

**Comment by LukeShortCloud** [comment]
Hey @jurassicplayer , thanks so much for the clarification! It seems like my issue may be related to this then: https://github.com/jurassicplayer/decky-autoflatpaks/issues/6

I don't have anything installed to `/etc/flatpak/installations.d/`. I have only ever installed Flatpaks using Discover and `flatpak install` from the CLI as the `deck` user. I know it is a bit more complicated than this, but if AutoFlatpaks were to run `sudo -u deck flatpak update` it should address this problem. We can safely assume that, on SteamOS, the user will always be `deck`.

You've got a really cool project here. Thanks for all of your hard work so far!
