### ISSUE TITLE
Auto Flatpaks not working on Beta Candidate and Beta Steam

### ISSUE THREAD

**Issue by 18209550** [jurassicplayer/decky-autoflatpaks#14]
Here's a video of the issue.

https://github.com/jurassicplayer/decky-autoflatpaks/assets/103085649/26dcbad4-8a5d-477a-9035-36fb06782dcc

**Comment by jurassicplayer** [comment]
Forgot that I never updated AutoFlatpaks to use global DFL.
It should be fixed now, if you want to install it manually or just wait until the update gets to the decky store.
