### ISSUE TITLE
Rendering error on SteamDeck Beta

### ISSUE THREAD

**Issue by SubElement** [jurassicplayer/decky-autoflatpaks#17]
Hello.

Running the latest Steam Deck Beta (OS 3.6.8 Build 20240626.100) with DeckyLoader v3.0.0-pre4 and AutoFlatpaks 1.6.6 and getting an error with rending causing this to pop up. This occurs when there is an update and you try to load the menu which lists what updates are available.

Please let me know if you need any further information.

![IMG_4928](https://github.com/jurassicplayer/decky-autoflatpaks/assets/7236925/0900708b-dd3b-473b-aef4-fe27014db29f)

**Comment by jurassicplayer** [comment]
Fixed in v1.6.7 (https://github.com/jurassicplayer/decky-autoflatpaks/commit/52f7984c5e6ea0f9babd6f3fa76276399dbd34d1)
- Changed to using ScrollPanel component built into DFL.
